default_language_version: python=3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: check-toml
  - id: check-yaml
    args:
    - --unsafe
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.7
  hooks:
  - id: ruff
    args:
    - --fix
  - id: ruff-format
