[tool.poetry]
name = "sakuramoti"
version = "0.1.0"
description = ""
authors = ["kololu777"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
torch = "^2.3.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
